require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2

Style/Documentation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/category.rb'
    - 'app/models/dish.rb'

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/state.rb'
    - 'app/models/dish.rb'
    - 'app/models/category.rb'